export interface App {
  id: number;
  name: string;
  path: string;
  iframeSrc: string;
  level: number;
}

export const apps: App[] = [
  {
    id: 1,
    name: "Random Number Generator",
    path: "/apps/random-number",
    iframeSrc: "https://lucent-semifreddo-6bce96.netlify.app/",
    level: 1,
  },
  {
    id: 2,
    name: "App 2",
    path: "/apps/app2",
    iframeSrc: "https://timely-bienenstitch-7158d3.netlify.app/",
    level: 1,
  },
  {
    id: 3,
    name: "App 3",
    path: "/apps/app3",
    iframeSrc: "https://incredible-boba-57ba5d.netlify.app/",
    level: 1,
  },
  {
    id: 4,
    name: "App 4",
    path: "/apps/app4",
    iframeSrc: "https://lovely-pavlova-2ac548.netlify.app/",
    level: 1,
  },
  {
    id: 5,
    name: "App 5",
    path: "/apps/app5",
    iframeSrc: "https://effulgent-pasca-40a1c9.netlify.app/",
    level: 1,
  },
  {
    id: 6,
    name: "App 6",
    path: "/apps/app5",
    iframeSrc: "https://prismatic-seahorse-3f7a5c.netlify.app/",
    level: 1,
  },
  {
    id: 7,
    name: "App 6",
    path: "/apps/app5",
    iframeSrc: "https://spiffy-brioche-4c4560.netlify.app/",
    level: 1,
  },
  {
    id: 8,
    name: "App 6",
    path: "/apps/app5",
    iframeSrc: "https://ephemeral-cheesecake-015964.netlify.app/",
    level: 1,
  },
  {
    id: 9,
    name: "App 6",
    path: "/apps/app5",
    iframeSrc: "https://celebrated-beignet-0ab5af.netlify.app/",
    level: 1,
  },
  {
    id: 10,
    name: "App 6",
    path: "/apps/app5",
    iframeSrc: "https://musical-lily-78ebf4.netlify.app/",
    level: 1,
  },
  {
    id: 11,
    name: "App 6",
    path: "/apps/app5",
    iframeSrc: "https://inspiring-croissant-aaea4d.netlify.app/",
    level: 1,
  },
  {
    id: 12,
    name: "App 6",
    path: "/apps/app5",
    iframeSrc: "https://candid-torrone-b66209.netlify.app/",
    level: 1,
  },
  {
    id: 13,
    name: "App 6",
    path: "/apps/app5",
    iframeSrc: "https://luminous-pasca-e1ac68.netlify.app/",
    level: 1,
  },
  {
    id: 14,
    name: "App 6",
    path: "/apps/app5",
    iframeSrc: "https://celebrated-taffy-b65b13.netlify.app/",
    level: 1,
  },
  {
    id: 15,
    name: "App 6",
    path: "/apps/app5",
    iframeSrc: "https://clever-snickerdoodle-b8c39d.netlify.app/",
    level: 1,
  },
  {
    id: 16,
    name: "App 16",
    path: "/apps/app5",
    iframeSrc: "https://lustrous-beignet-a24a47.netlify.app/",
    level: 1,
  },
  {
    id: 17,
    name: "Date Calculator",
    path: "/apps/...",
    iframeSrc: "https://charming-rabanadas-51a703.netlify.app/",
    level: 2,
  },
  {
    id: 18,
    name: "Theme Switcher",
    path: "/apps/...",
    iframeSrc: "https://symphonious-piroshki-ca71c2.netlify.app/",
    level: 2,
  },
  {
    id: 19,
    name: "Key Counter",
    path: "/apps/...",
    iframeSrc: "https://resplendent-elf-6a61c1.netlify.app/",
    level: 2,
  },
  {
    id: 20,
    name: "Step Indicator",
    path: "/apps/...",
    iframeSrc: "https://benevolent-gnome-e33a30.netlify.app/",
    level: 2,
  },
  {
    id: 21,
    name: "Decimal-Binary Converter	",
    path: "/apps/...",
    iframeSrc: "https://tubular-brioche-5a2bbf.netlify.app/",
    level: 2,
  },
  {
    id: 22,
    name: "Sortable List With Drag And Drop",
    path: "/apps/...",
    iframeSrc: "https://astounding-chimera-95f2bf.netlify.app/",
    level: 2,
  },
  {
    id: 23,
    name: "Image Slider	",
    path: "/apps/...",
    iframeSrc: "https://superb-heliotrope-a182fc.netlify.app/",
    level: 2,
  },
  {
    id: 24,
    name: "Countdown Timer	",
    path: "/apps/...",
    iframeSrc: "https://melodic-cendol-1ddcb3.netlify.app/",
    level: 2,
  },
  {
    id: 25,
    name: "Todo List	",
    path: "/apps/...",
    iframeSrc: "https://meek-souffle-785242.netlify.app/",
    level: 2,
  },
  {
    id: 26,
    name: "Range Control	",
    path: "/apps/...",
    iframeSrc: "https://lively-blancmange-a00ba0.netlify.app/",
    level: 2,
  },
  {
    id: 27,
    name: "Weight Converter",
    path: "/apps/...",
    iframeSrc: "https://chic-khapse-13d3fe.netlify.app/",
    level: 2,
  },
  {
    id: 27,
    name: "Detect Browser	",
    path: "/apps/...",
    iframeSrc: "https://reliable-pithivier-640794.netlify.app/",
    level: 2,
  },
  {
    id: 28,
    name: "Calculator	",
    path: "/apps/...",
    iframeSrc: "https://roaring-speculoos-9b2532.netlify.app/",
    level: 2,
  },
  {
    id: 29,
    name: "Age Calculator	",
    path: "/apps/...",
    iframeSrc: "https://cool-dodol-d5b2cc.netlify.app/",
    level: 2,
  },
  {
    id: 30,
    name: "Digital Clock	",
    path: "/apps/...",
    iframeSrc: "https://ubiquitous-klepon-29f6bc.netlify.app/",
    level: 2,
  },
  {
    id: 30,
    name: "Stop Watch	",
    path: "/apps/...",
    iframeSrc: "https://venerable-halva-38027d.netlify.app/",
    level: 2,
  },
  {
    id: 31,
    name: "Joke Generator	",
    path: "/apps/...",
    iframeSrc: "https://chic-douhua-da8067.netlify.app/",
    level: 2,
  },
  {
    id: 32,
    name: "Fibonacci Generator	",
    path: "/apps/...",
    iframeSrc: "https://frolicking-gingersnap-81eb24.netlify.app/",
    level: 2,
  },
  {
    id: 33,
    name: "Calendar	",
    path: "/apps/...",
    iframeSrc: "https://remarkable-macaron-98cbe2.netlify.app/",
    level: 2,
  },
  {
    id: 34,
    name: "Product Counter",
    path: "/apps/...",
    iframeSrc: "https://dazzling-banoffee-acfe6e.netlify.app/",
    level: 2,
  },
  {
    id: 35,
    name: "Email Validation	",
    path: "/apps/...",
    iframeSrc: "https://merry-cajeta-6bc82d.netlify.app/",
    level: 2,
  },
  {
    id: 36,
    name: "Form Validation	",
    path: "/apps/...",
    iframeSrc: "https://inquisitive-ganache-d85029.netlify.app/",
    level: 2,
  },
  {
    id: 37,
    name: "Percentage Calculator	",
    path: "/apps/...",
    iframeSrc: "https://delightful-salmiakki-6a9f1a.netlify.app/",
    level: 2,
  },
  {
    id: 38,
    name: "Love Calculator	",
    path: "/apps/...",
    iframeSrc: "https://resplendent-fenglisu-02a5f7.netlify.app/",
    level: 2,
  },
  {
    id: 39,
    name: "Tip Calculator	",
    path: "/apps/...",
    iframeSrc: "https://super-clafoutis-e39fb3.netlify.app/",
    level: 2,
  },
  {
    id: 40,
    name: "Analog Clock	",
    path: "/apps/...",
    iframeSrc: "https://super-clafoutis-e39fb3.netlify.app/",
    level: 2,
  },
  {
    id: 41,
    name: "Customize The Parrot	",
    path: "/apps/...",
    iframeSrc: "https://super-clafoutis-e39fb3.netlify.app/",
    level: 2,
  },
  {
    id: 42,
    name: "Halloween Party	",
    path: "/apps/...",
    iframeSrc: "https://keen-duckanoo-b9f982.netlify.app/",
    level: 2,
  },
  {
    id: 43,
    name: "Weather App	",
    path: "/apps/...",
    iframeSrc: "https://heartfelt-caramel-695b45.netlify.app/",
    level: 2,
  },
  {
    id: 44,
    name: "New Year Counter	",
    path: "/apps/...",
    iframeSrc: "https://sprightly-cactus-3fbf33.netlify.app/",
    level: 2,
  },
  {
    id: 45,
    name: "Meaning Of Your Name	",
    path: "/apps/...",
    iframeSrc: "https://silly-fox-ccdfe8.netlify.app/",
    level: 2,
  },
  {
    id: 46,
    name: "Coin Flip",
    path: "/apps/...",
    iframeSrc: "https://gilded-syrniki-b834d6.netlify.app/",
    level: 2,
  },
  {
    id: 47,
    name: "Height Converter	",
    path: "/apps/...",
    iframeSrc: "https://gilded-syrniki-b834d6.netlify.app/",
    level: 2,
  },
  {
    id: 47,
    name: "Drag And Drop	",
    path: "/apps/...",
    iframeSrc: "https://heroic-swan-76e763.netlify.app/",
    level: 2,
  },
  {
    id: 48,
    name: "Accordion",
    path: "/apps/...",
    iframeSrc: "https://cheerful-muffin-886995.netlify.app/",
    level: 2,
  },
  {
    id: 49,
    name: "Show / Hide Password	",
    path: "/apps/...",
    iframeSrc: "https://gorgeous-mandazi-c9fb8b.netlify.app/",
    level: 2,
  },
  {
    id: 50,
    name: "Billionaires Table	",
    path: "/apps/...",
    iframeSrc: "https://sunny-cajeta-5dd982.netlify.app/",
    level: 2,
  },
  {
    id: 51,
    name: "Pet Finder	",
    path: "/apps/...",
    iframeSrc: "https://sparkly-gecko-315dcf.netlify.app/",
    level: 2,
  },
  {
    id: 52,
    name: "Exchange Rate Calculator		",
    path: "/apps/...",
    iframeSrc: "https://exquisite-maamoul-2036ef.netlify.app/",
    level: 2,
  },
  {
    id: 53,
    name: "Loan Calculator	",
    path: "/apps/...",
    iframeSrc: "https://heroic-salamander-1c20f4.netlify.app/",
    level: 2,
  },
  {
    id: 54,
    name: "Draggable Container",
    path: "/apps/...",
    iframeSrc: "https://lustrous-bubblegum-d531c4.netlify.app/",
    level: 2,
  },
  {
    id: 55,
    name: "BMI Calculator	",
    path: "/apps/...",
    iframeSrc: "https://lustrous-bubblegum-d531c4.netlify.app/",
    level: 2,
  },
  {
    id: 56,
    name: "Lorem Ipsum Generator	",
    path: "/apps/...",
    iframeSrc: "https://unique-scone-74ef39.netlify.app/",
    level: 2,
  },
  {
    id: 57,
    name: "Typing Effect	",
    path: "/apps/...",
    iframeSrc: "https://luminous-maamoul-f1cc93.netlify.app/",
    level: 2,
  },
  {
    id: 58,
    name: "Read More / Less Button	",
    path: "/apps/...",
    iframeSrc: "https://leafy-cassata-bfdd45.netlify.app/",
    level: 2,
  },
  {
    id: 59,
    name: "Hexadecimal Clock	",
    path: "/apps/...",
    iframeSrc: "https://sweet-cuchufli-a3b3e9.netlify.app/",
    level: 2,
  },
  {
    id: 60,
    name: "Palindrome Checker	",
    path: "/apps/...",
    iframeSrc: "https://sweet-cuchufli-a3b3e9.netlify.app/",
    level: 2,
  },
];
